#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J polishing
#SBATCH --mail-type=ALL
#SBATCH --mail-user jakob.siljebo@gmail.com
#SBATCH --output=%x.%j.out

module load bioinfo-tools Pilon/1.24

java -jar $PILON_HOME/pilon.jar --genome assembly.fasta --frags sorted_mapped_reads.bam.bai --output pilon_output --threads 2

